### DISCUSSION TITLE
Can i integrate two Blauberg KOMFORT-devices?

### DISCUSSION THREAD

**Discussion by Schelfengerch** [gracingpro/blauberg-homeassistant#3] [General]
Hi,
can i integrale two Blauberg Komfort devices to a home Assistant-Installation? 
A  Komfort EC D5B 180-E S21 and a Komfort EC SB 350-E S21?
What does the configuration file look like?

many greetings 

wolfgang

**Comment by gracingpro** [comment]
Hi Wolfgang,

Thank you for reaching out and asking about the integration of multiple Blauberg Komfort devices with Home Assistant.

As per your initial question, indeed, the current solution does not natively support multiple devices. However, you can integrate more than one device by setting up a new instance for each device with unique settings.

For each device, you will need to adjust several parameters:

- MQTT topic name: This should be unique for each device to avoid message conflicts.
- API port: Make sure that each device is using a unique port.
- Service and container name in the docker-compose file: Just like the other parameters, these should also be unique for each instance.

Here's an example of what the configuration file might look like for a second device:

```ini
[Vent]
ip = 192.168.0.253 # Or whatever the IP address is for your second device

[MQTT]
user = mqtt_user
topic = Blauberg2 # Or whatever your unique topic for the second device
homeassistant_topic = homeassistant
password = mqtt_password
host = host.docker.internal
port = 1883
scrape_interval = 15

[Blauberg]
api_token = 123 # Or whatever your unique API token is for the second device
api_port = 8007 # A unique port number for the second device
```

And your docker-compose file would look something like this:

```yml
version: "2"
services:
  blauberg-homeassistant2:  # A unique service name for the second device
    image: gracingpro/blauberg-homeassistant:latest
    container_name: blauberg-homeassistant2  # A unique container name for the second device
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8007:8007"  # A unique port mapping for the second device
    volumes:
      - ./config2.ini:/opt/blauberg/config.ini  # Pointing to a unique configuration file for the second device
    restart: always
```

Please adjust these settings according to your own network setup. By duplicating the services and providing unique settings for each device, you should be able to control multiple Blauberg devices from Home Assistant.

I hope this helps. Feel free to ask if you have further questions.

Best regards,

Dmitry
